import type { DemoPhoto } from "@/types/memory-trail";

/**
 * Seeded demo library for the Memory Trail MVP. Images are reused from the
 * existing /mvp photo library (public/library/*.jpg, already used by
 * /mvp's Photo Finder) -- real photos, but the event/people/location fields
 * below are authored fictional metadata built for this scenario, not the
 * original Photo Finder dataset's own captions.
 *
 * The scenario: the user is trying to find ONE concert photo with Aisha,
 * outdoor stage lights, and fireworks (IMG_4081, the target). IMG_4089 is
 * from the literal same event/stage/date -- the "near match" the user opens
 * first -- but does not show the fireworks moment itself.
 */
export const DEMO_PHOTOS: DemoPhoto[] = [
  {
    id: "IMG_4081",
    imageUrl: "/library/IMG_4081.jpg",
    date: "2023-06-24",
    approximateTime: "night",
    location: "Mumbai",
    people: ["Aisha"],
    event: "Diwali Fest Concert",
    visualTags: ["concert", "outdoor stage", "night", "orange stage lights", "fireworks", "crowd"],
    sceneDescription: "Festival stage with an orange glowing arch of lights and blue-green screen, a person standing with arms raised among a crowd silhouette.",
    semanticCaption: "Me and Aisha at that outdoor concert, the stage lit up orange with fireworks going off overhead.",
  },
  {
    id: "IMG_4089",
    imageUrl: "/library/IMG_4089.jpg",
    date: "2023-06-24",
    approximateTime: "night",
    location: "Mumbai",
    people: ["Aisha"],
    event: "Diwali Fest Concert",
    visualTags: ["concert", "outdoor stage", "night", "orange stage lights", "crowd"],
    sceneDescription: "Same festival stage with orange glowing arch and blue-green screen, crowd silhouette, a couple of people with raised arms.",
    semanticCaption: "Another shot from that same concert night with Aisha, before the fireworks started.",
  },
  {
    id: "IMG_4004",
    imageUrl: "/library/IMG_4004.jpg",
    date: "2019-07-20",
    approximateTime: "night",
    location: "Pune",
    people: ["Rohan"],
    event: "Riverside Music Fest",
    visualTags: ["concert", "crowd", "hands raised", "heart hands", "stage lights", "live music"],
    sceneDescription: "Crowd at a live concert with hands raised and two hands forming a heart shape in the foreground, warm stage spotlights behind.",
    semanticCaption: "That riverside music festival with Rohan, warm orange spotlights.",
  },
  {
    id: "IMG_4007",
    imageUrl: "/library/IMG_4007.jpg",
    date: "2022-12-10",
    approximateTime: "night",
    location: "Bangalore",
    people: ["Meera"],
    event: "Winter Beats Concert",
    visualTags: ["concert", "crowd", "raised hand", "stage glare", "band", "orange haze"],
    sceneDescription: "Back view of a concert audience with one raised hand and a bright orange-white glare from the stage, band silhouettes in the haze.",
    semanticCaption: "Winter concert with Meera, hazy orange stage glare.",
  },
  {
    id: "IMG_4015",
    imageUrl: "/library/IMG_4015.jpg",
    date: "2023-02-18",
    approximateTime: "night",
    location: "Delhi",
    people: ["Rohan"],
    event: "Arena Night Concert",
    visualTags: ["concert", "arena", "crowd", "yellow lights", "stage", "large venue"],
    sceneDescription: "Large arena concert with a packed crowd silhouette and bright yellow stage lights with white beams above.",
    semanticCaption: "That huge arena show with Rohan, bright yellow beams.",
  },
  {
    id: "IMG_4024",
    imageUrl: "/library/IMG_4024.jpg",
    date: "2021-09-25",
    approximateTime: "night",
    location: "Pune",
    people: [],
    event: "Smoke & Sound Concert",
    visualTags: ["concert", "band", "smoke", "stage lights", "orange haze", "live music"],
    sceneDescription: "Band on a smoky stage under rows of square stage lights, orange-brown haze, audience hands raised in the dark foreground.",
    semanticCaption: "A smoky, hazy concert, band barely visible through the haze.",
  },
  {
    id: "IMG_4035",
    imageUrl: "/library/IMG_4035.jpg",
    date: "2022-10-14",
    approximateTime: "night",
    location: "Bangalore",
    people: ["Meera"],
    event: "Violet Nights Concert",
    visualTags: ["concert", "band", "purple lighting", "violet", "crowd", "phones"],
    sceneDescription: "Band performing on stage under purple and violet lighting in front of a colourful circular-pattern backdrop; audience silhouettes with phones in the foreground.",
    semanticCaption: "Purple-lit concert with Meera, everyone filming on their phones.",
  },
  {
    id: "IMG_4061",
    imageUrl: "/library/IMG_4061.jpg",
    date: "2023-04-02",
    approximateTime: "night",
    location: "Delhi",
    people: [],
    event: "Worship Night Concert",
    visualTags: ["concert", "blue lighting", "purple", "raised hands", "crowd", "lyrics screen"],
    sceneDescription: "Church-style concert with raised hands silhouetted against blue and purple stage beams; lyrics text visible on screen at the top.",
    semanticCaption: "That worship night concert, blue and purple beams, everyone's hands up.",
  },
  {
    id: "IMG_4074",
    imageUrl: "/library/IMG_4074.jpg",
    date: "2022-06-18",
    approximateTime: "night",
    location: "Goa",
    people: ["Rohan"],
    event: "Green Laser Fest",
    visualTags: ["concert", "festival", "green laser", "stage lights", "crowd", "silhouette"],
    sceneDescription: "Festival stage with green laser and stage lights, one person with arms raised in silhouette in front of a crowd.",
    semanticCaption: "Goa festival with Rohan, bright green lasers over the crowd.",
  },
  {
    id: "IMG_4093",
    imageUrl: "/library/IMG_4093.jpg",
    date: "2022-07-09",
    approximateTime: "evening",
    location: "Pune",
    people: [],
    event: "Skull & Bones Fest",
    visualTags: ["concert", "festival", "metal band", "blue lights", "outdoor stage", "crowd"],
    sceneDescription: "Wide shot of a metal band on an outdoor festival stage under blue lights, with a dense crowd in front and a skull banner behind.",
    semanticCaption: "That metal festival, blue-lit outdoor stage, skull banner behind the band.",
  },
  {
    id: "IMG_4099",
    imageUrl: "/library/IMG_4099.jpg",
    date: "2021-11-20",
    approximateTime: "night",
    location: "Mumbai",
    people: [],
    event: "Solo Singer Night",
    visualTags: ["concert", "singer", "microphone", "blue lights", "white beams", "stage"],
    sceneDescription: "Singer in an embellished white jacket performing on stage with a handheld microphone, bright white beams and blue backdrop.",
    semanticCaption: "A solo singer in a white jacket, blue stage backdrop.",
  },
  {
    id: "IMG_4110",
    imageUrl: "/library/IMG_4110.jpg",
    date: "2021-11-20",
    approximateTime: "night",
    location: "Mumbai",
    people: [],
    event: "Guitar Jam Session",
    visualTags: ["concert", "guitarist", "electric guitar", "amplifier", "stage", "band"],
    sceneDescription: "Guitarist in dark clothes playing a yellow-necked electric guitar on stage next to an amplifier rack.",
    semanticCaption: "The guitarist's solo at that small venue show.",
  },
  {
    id: "IMG_4045",
    imageUrl: "/library/IMG_4045.jpg",
    date: "2023-05-06",
    approximateTime: "night",
    location: "Jaipur",
    people: ["Rohan"],
    event: "New Year Fireworks",
    visualTags: ["fireworks", "castle", "night", "crowd", "phones", "theme park"],
    sceneDescription: "Fireworks above a lit fairy-tale castle at night with a huge crowd holding up phones in the foreground.",
    semanticCaption: "Fireworks over the castle with Rohan, everyone filming on their phones.",
  },
  {
    id: "IMG_4052",
    imageUrl: "/library/IMG_4052.jpg",
    date: "2023-01-14",
    approximateTime: "night",
    location: "Goa",
    people: [],
    event: "Winter Festival Fireworks",
    visualTags: ["fireworks", "night", "water", "pyrotechnics", "show", "blue light"],
    sceneDescription: "Blue and white fireworks and pyrotechnic fountains over water at night with light beams.",
    semanticCaption: "Fireworks over the water at that winter festival.",
  },
  {
    id: "IMG_4374",
    imageUrl: "/library/IMG_4374.jpg",
    date: "2021-12-25",
    approximateTime: "evening",
    location: "Delhi",
    people: ["Aisha", "Family"],
    event: "Christmas Dinner",
    visualTags: ["dinner", "family", "indoor", "christmas", "gathering"],
    sceneDescription: "Large family gathered around a dining table with a white tablecloth and red poinsettia centrepiece under a chandelier, warm orange light.",
    semanticCaption: "Christmas dinner with Aisha and the family, warm chandelier light.",
  },
  {
    id: "IMG_4456",
    imageUrl: "/library/IMG_4456.jpg",
    date: "2023-01-18",
    approximateTime: "afternoon",
    location: "Bangalore",
    people: [],
    event: "Tech Conference 2023",
    visualTags: ["conference", "panel", "stage", "blue lighting", "audience", "event"],
    sceneDescription: "Wide-angle shot of a conference panel on a round white stage under blue lighting with cameras and audience seated around.",
    semanticCaption: "That tech conference panel, blue-lit round stage.",
  },
  {
    id: "IMG_4523",
    imageUrl: "/library/IMG_4523.jpg",
    date: "2022-12-03",
    approximateTime: "afternoon",
    location: "Paris",
    people: ["Meera"],
    event: "Cafe Meetup",
    visualTags: ["cafe", "outdoor", "coffee", "winter coats", "cobblestones"],
    sceneDescription: "Black and white photo of three women sitting at an outdoor cafe table on cobblestones holding coffee cups, in winter coats.",
    semanticCaption: "Coffee with Meera at that cobblestone cafe in Paris.",
  },
  {
    id: "IMG_4483",
    imageUrl: "/library/IMG_4483.jpg",
    date: "2022-12-28",
    approximateTime: "afternoon",
    location: "Goa",
    people: ["Rohan"],
    event: "Goa Beach Trip",
    visualTags: ["beach", "goa", "dog", "sand", "overcast", "sea"],
    sceneDescription: "Overcast Goa beach scene with a dog on the sand and the sea behind, a lifeguard post nearby.",
    semanticCaption: "That overcast day on the Goa beach with Rohan.",
  },
  {
    id: "IMG_4492",
    imageUrl: "/library/IMG_4492.jpg",
    date: "2022-01-08",
    approximateTime: "afternoon",
    location: "Goa",
    people: [],
    event: "Goa Beach Trip",
    visualTags: ["beach", "goa", "agonda", "palm trees", "sand", "empty"],
    sceneDescription: "Empty Agonda beach in Goa with palm trees along a headland and open sand.",
    semanticCaption: "That empty stretch of beach in Agonda, Goa.",
  },
  {
    id: "IMG_4499",
    imageUrl: "/library/IMG_4499.jpg",
    date: "2023-01-04",
    approximateTime: "evening",
    location: "Goa",
    people: ["Meera"],
    event: "Goa Beach Trip",
    visualTags: ["beach", "goa", "candolim", "beach shack", "string lights"],
    sceneDescription: "Candolim beach shack in Goa with string lights, sun loungers and a checked tablecloth.",
    semanticCaption: "Dinner at that beach shack in Candolim with Meera, string lights overhead.",
  },
  {
    id: "IMG_4191",
    imageUrl: "/library/IMG_4191.jpg",
    date: "2022-12-27",
    approximateTime: "evening",
    location: "Udaipur",
    people: [],
    event: "Udaipur Getaway",
    visualTags: ["sunset", "palace", "fort", "hilltop", "dramatic sky", "udaipur"],
    sceneDescription: "Dramatic sunset over a hilltop palace and fort in Udaipur.",
    semanticCaption: "Sunset over the palace in Udaipur.",
  },
  {
    id: "IMG_8313",
    imageUrl: "/library/IMG_8313.jpg",
    date: "2023-04-29",
    approximateTime: "evening",
    location: "Himachal",
    people: [],
    event: "Himachal Road Trip",
    visualTags: ["sunset", "snow mountains", "panorama", "kalpa", "golden peaks", "himachal"],
    sceneDescription: "Golden sunset panorama over snow-capped peaks near Kalpa, Himachal.",
    semanticCaption: "Golden peaks at sunset on that Himachal road trip.",
  },
  {
    id: "IMG_8305",
    imageUrl: "/library/IMG_8305.jpg",
    date: "2022-05-21",
    approximateTime: "evening",
    location: "Himachal",
    people: [],
    event: "Himachal Road Trip",
    visualTags: ["sunset", "pine", "silhouette", "dusk", "hills", "himachal"],
    sceneDescription: "Pine tree silhouettes against a grey dusk sky over the Himachal hills.",
    semanticCaption: "Pine silhouettes at dusk, same Himachal trip.",
  },
  {
    id: "IMG_4432",
    imageUrl: "/library/IMG_4432.jpg",
    date: "2022-10-02",
    approximateTime: "afternoon",
    location: "Mumbai",
    people: [],
    event: "Evening Walk",
    visualTags: ["dog", "cocker spaniel", "bench", "cobblestones", "pet", "outdoor"],
    sceneDescription: "Brown cocker spaniel sitting on cobblestones next to a wooden bench, looking up.",
    semanticCaption: "That cocker spaniel we met on our walk.",
  },
  {
    id: "IMG_4441",
    imageUrl: "/library/IMG_4441.jpg",
    date: "2021-05-16",
    approximateTime: "afternoon",
    location: "Mumbai",
    people: ["Rohan"],
    event: "Park Visit",
    visualTags: ["dog", "park", "grass", "pet", "outdoor"],
    sceneDescription: "Fluffy black dog lying on green grass in a park with its tongue out, a person's shoe in the corner.",
    semanticCaption: "The park with Rohan and that fluffy black dog.",
  },
  {
    id: "IMG_4340",
    imageUrl: "/library/IMG_4340.jpg",
    date: "2022-07-30",
    approximateTime: "afternoon",
    location: "Goa",
    people: [],
    event: "Sailing Trip",
    visualTags: ["cooking", "boat", "galley", "sea", "outdoor kitchen"],
    sceneDescription: "Man cooking at a stainless-steel outdoor galley on a boat with the sea behind him.",
    semanticCaption: "Cooking on the boat during that sailing trip.",
  },
  {
    id: "IMG_4704",
    imageUrl: "/library/IMG_4704.jpg",
    date: "2023-01-21",
    approximateTime: "afternoon",
    location: "Delhi",
    people: [],
    event: "Market Day",
    visualTags: ["cooking", "market", "steam", "stock pots", "food stall"],
    sceneDescription: "Man lifting the lid off a huge pot with steam rising, among large stock pots under a market canopy.",
    semanticCaption: "That huge steaming pot at the market.",
  },
  {
    id: "IMG_8281",
    imageUrl: "/library/IMG_8281.jpg",
    date: "2022-02-19",
    approximateTime: "afternoon",
    location: "Rajasthan",
    people: [],
    event: "Village Visit",
    visualTags: ["cooking", "clay stove", "courtyard", "firewood", "village"],
    sceneDescription: "Woman cooking on a clay stove in a courtyard with firewood and steel pots.",
    semanticCaption: "The clay stove cooking in that village courtyard.",
  },
  {
    id: "IMG_8300",
    imageUrl: "/library/IMG_8300.jpg",
    date: "2019-08-15",
    approximateTime: "afternoon",
    location: "Malawi",
    people: [],
    event: "Village Visit",
    visualTags: ["cooking", "outdoor", "brick wall", "basin", "village"],
    sceneDescription: "Woman squatting outdoors stirring a pot beside a basin of food in front of a brick wall.",
    semanticCaption: "Cooking by the brick wall on that village visit.",
  },
  {
    id: "IMG_8301",
    imageUrl: "/library/IMG_8301.jpg",
    date: "2023-03-21",
    approximateTime: "afternoon",
    location: "Rajasthan",
    people: [],
    event: "Festival Cooking",
    visualTags: ["cooking", "village", "courtyard", "festival food", "wooden paddle"],
    sceneDescription: "Two older women stirring a large steaming pot with long wooden paddles in a village courtyard.",
    semanticCaption: "That festival cooking day, two women stirring the big pot.",
  },
  {
    id: "IMG_4508",
    imageUrl: "/library/IMG_4508.jpg",
    date: "2020-11-08",
    approximateTime: "evening",
    location: "Kerala",
    people: [],
    event: "Fishing Trip",
    visualTags: ["fishermen", "dusk", "nets", "water", "silhouette", "sunset"],
    sceneDescription: "Fishermen with nets silhouetted against a pink dusk sky over the water.",
    semanticCaption: "Fishermen at dusk on that Kerala trip.",
  },
];
